/* Copyright (C) 2023-2026 QuantumNous
This program is free software under the GNU Affero General Public License version 3 or later. */
import type { CanvasBusinessTermKind } from './business-terms'
import type { CanvasBusinessFactKind } from './types'

export const factKindLabels: Record<CanvasBusinessFactKind, string> = {
  task: 'Task',
  output: 'Task result',
  debt: 'Point debt',
  repayment: 'Debt repayment',
  quote: 'Quote',
  lot: 'Point Lots',
  ledger: 'Point ledger',
  allocation: 'Point allocation',
  order: 'Recharge order',
  payment: 'Payment event',
  pointReturn: 'Point return',
  refund: 'Refund',
  recovery: 'Recovery case',
  cost: 'Provider cost',
  reconciliation: 'Reconciliation decision',
}
export const factStatusTerms: Partial<
  Record<CanvasBusinessFactKind, CanvasBusinessTermKind>
> = {
  task: 'taskExecutionStatus',
  output: 'taskExecutionStatus',
  lot: 'pointLotType',
  ledger: 'ledgerEvent',
  order: 'rechargeOrderStatus',
  refund: 'refundStatus',
  recovery: 'recoveryStatus',
}
export const factValueLabels: Record<string, string> = {
  ACTIVE: 'Valid',
  CONSUMED: 'Consumed',
  EXPIRED: 'Expired',
  REPLACED_SAME_PRICE: 'Replaced at the same price',
  REPLACED_LOWER_PRICE: 'Replaced at a lower price',
  REPLACED_HIGHER_PRICE: 'Replaced at a higher price',
  FROZEN: 'Frozen',
  SETTLED: 'Settled',
  RELEASED: 'Released',
  TRANSFERRED: 'Transferred',
  PENDING: 'Pending',
  POSTED: 'Posted',
  FAILED: 'Failed',
  VOID: 'Void',
  CONFIRMED: 'Confirmed',
  APPROVED: 'Approved',
  REJECTED: 'Rejected',
  REVOKED: 'Revoked',
  CHARGE: 'Charge',
  REFUND: 'Refund',
  ADJUSTMENT: 'Adjustment',
  PAYMENT: 'Payment',
  CHARGEBACK: 'Chargeback',
  FEE: 'Fee',
  FEE_REFUND: 'Fee refund',
  SETTLEMENT_ADJUSTMENT: 'Settlement adjustment',
  SUCCESS_COST: 'Successful task cost',
  CONFIRMED_FAILURE_LOSS: 'Confirmed failure loss',
  RECONCILIATION_TIMEOUT_LOSS: 'Reconciliation timeout loss',
  PENDING_RECOVERY: 'Pending recovery',
  RECOVERED_AMOUNT: 'Recovered amount',
  OTHER_VARIABLE_COST: 'Other variable cost',
  RECHARGE_CODE: 'Recharge code',
  REGISTRATION_BONUS: 'Registration bonus',
  INVITE_BONUS: 'Invite bonus',
  PROMOTION: 'Promotion',
  CUSTOMER_SERVICE: 'Customer service',
  MANUAL_GRANT: 'Manual grant',
  GRACE_TRANSFER: 'Grace transfer',
  OPEN: 'Outstanding',
  PARTIALLY_REPAID: 'Partially repaid',
  REPAID: 'Repaid',
}
export const factFieldLabels: Record<string, string> = {
  discountPoints: 'Discount points',
  promotionVersion: 'Promotion version',
  pricePlanCode: 'Price plan',
  pricePlanVersion: 'Version',
  priceVersion: 'Price version',
  basePoints: 'Base points',
  executionOrigin: 'Execution source',
  executionStatus: 'Execution',
  billingStatus: 'Customer billing',
  reconciliationStatus: 'Provider reconciliation',
  upstreamTaskId: 'Upstream task ID',
  quotedPoints: 'Quoted points',
  completedAt: 'Completed at',
  billingFinalizedAt: 'Billing finalized at',
  allocatedPoints: 'Allocated points',
  settledPoints: 'Settled points',
  releasedPoints: 'Released points',
  transferredPoints: 'Transferred points',
  paidSettledPoints: 'Settled Paid points',
  bonusSettledPoints: 'Settled Bonus points',
  expiresAt: 'Expires at',
  consumedAt: 'Consumed at',
  confirmedAt: 'Confirmed at',
  lotType: 'Type',
  sourceType: 'Source',
  rechargeOrderNumber: 'Recharge order',
  initialPoints: 'Initial points',
  remainingPoints: 'Remaining points',
  availablePoints: 'Available points',
  reservedPoints: 'Reserved points',
  originalExpiresAt: 'Original expiry',
  closedAt: 'Closed at',
  eventType: 'Event',
  eventPoints: 'Points',
  remainingDelta: 'Remaining delta',
  reservedDelta: 'Reserved delta',
  remainingAfter: 'Remaining after operation',
  reservedAfter: 'Reserved after operation',
  reason: 'Reason',
  actor: 'Operator',
  finalizedAt: 'Finalized at',
  listedAmountMinor: 'Listed amount',
  currency: 'Currency',
  paidAt: 'Paid at',
  cancelledAt: 'Cancelled at',
  paymentEvent: 'Event',
  signedAmountMinor: 'Signed amount',
  postedAt: 'Posted at',
  cashEffect: 'Cash effect',
  cashAmountMinor: 'Externally confirmed amount',
  pointsRequested: 'Calculated points',
  pointsClawedBack: 'Recovered points',
  pointsOutstanding: 'Outstanding points',
  pointsDue: 'Points due',
  pointsRecovered: 'Recovered points',
  costEvent: 'Event',
  classification: 'Classification',
  signedAmount: 'Signed amount',
  exchangeRate: 'Exchange rate snapshot',
  normalizedAmountMinor: 'Normalized cost (CNY minor units)',
  decidedAt: 'Decision time',
  referenceAmountMinor: 'Refund reference amount',
  pointsReturned: 'Returned points',
  originalOrderAmountMinor: 'Original recharge amount',
  originalPurchasedPoints: 'Original purchased points',
  cumulativeReturnedPointsBefore: 'Returned points before this return',
  cumulativeReturnedPointsAfter: 'Returned points after this return',
  cumulativeReferenceAmountMinorBefore: 'Reference amount before this return',
  cumulativeReferenceAmountMinorAfter: 'Reference amount after this return',
}
export const factStatusValues: Record<CanvasBusinessFactKind, string[]> = {
  task: ['ACCEPTED', 'PROCESSING', 'SUCCEEDED', 'CONFIRMED_FAILED', 'UNKNOWN'],
  output: [
    'ACCEPTED',
    'PROCESSING',
    'SUCCEEDED',
    'CONFIRMED_FAILED',
    'UNKNOWN',
  ],
  debt: ['OPEN', 'PARTIALLY_REPAID', 'REPAID'],
  repayment: ['POSTED'],
  quote: [
    'ACTIVE',
    'CONSUMED',
    'EXPIRED',
    'REPLACED_SAME_PRICE',
    'REPLACED_LOWER_PRICE',
    'REPLACED_HIGHER_PRICE',
  ],
  lot: ['PAID', 'BONUS', 'GRACE_BONUS'],
  ledger: [
    'ISSUE',
    'FREEZE',
    'SETTLE',
    'RELEASE',
    'EXPIRE',
    'CLAWBACK',
    'ADJUSTMENT_DEBIT',
    'TRANSFER_OUT',
    'TRANSFER_IN',
    'DEBT_REPAYMENT',
    'POINT_RETURN',
  ],
  allocation: ['FROZEN', 'SETTLED', 'RELEASED', 'TRANSFERRED'],
  order: ['CREATED', 'PAYMENT_PENDING', 'PAID', 'CODE_ACTIVATED', 'CANCELLED'],
  payment: ['PENDING', 'POSTED', 'FAILED', 'VOID'],
  pointReturn: ['POSTED'],
  refund: [
    'REQUESTED',
    'APPROVED',
    'CASH_POSTED',
    'POINTS_PROCESSED',
    'PARTIAL_RECOVERY',
    'COMPLETED',
    'REJECTED',
  ],
  recovery: [
    'OPEN',
    'PARTIALLY_RECOVERED',
    'RECOVERED',
    'WRITTEN_OFF',
    'CLOSED',
  ],
  cost: ['PENDING', 'CONFIRMED', 'VOID'],
  reconciliation: ['PENDING', 'APPROVED', 'REJECTED', 'REVOKED'],
}
